// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadSettings():Promise<services.Settings>;

export function SaveSettings(arg1:services.Settings):Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<string>;
