// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {services} from '../models';

export function CreateChat(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListChats():Promise<Array<core.ChatSummary>>;

export function LoadAPIKeys():Promise<services.APIKeys>;

export function LoadOneChat(arg1:string):Promise<core.Chat>;

export function LoadSettings():Promise<services.Settings>;

export function ReloadApp(arg1:Array<any>):Promise<void>;

export function SaveAPIKeys(arg1:services.APIKeys):Promise<void>;

export function SaveSettings(arg1:services.Settings):Promise<void>;

export function SendPrompt(arg1:string,arg2:string,arg3:string):Promise<string>;
